//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Guesstimate.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Guesstimate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to add this task to the project scope?.
        /// </summary>
        internal static string AddTaskForm_AddTaskToScope {
            get {
                return ResourceManager.GetString("AddTaskForm_AddTaskToScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes?.
        /// </summary>
        internal static string AddTaskForm_AddTaskToScopeCaption {
            get {
                return ResourceManager.GetString("AddTaskForm_AddTaskToScopeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save your changes to this task?.
        /// </summary>
        internal static string EditTaskForm_SaveChanges {
            get {
                return ResourceManager.GetString("EditTaskForm_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes?.
        /// </summary>
        internal static string EditTaskForm_SaveChangesCaption {
            get {
                return ResourceManager.GetString("EditTaskForm_SaveChangesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Guesstimation Project?.
        /// </summary>
        internal static string ProjectEstimateForm_LoadGuesstimationProject {
            get {
                return ResourceManager.GetString("ProjectEstimateForm_LoadGuesstimationProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Guesstimation Project|*.json.
        /// </summary>
        internal static string ProjectEstimateForm_LoadGuesstimationProjectFilter {
            get {
                return ResourceManager.GetString("ProjectEstimateForm_LoadGuesstimationProjectFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save your current Guesstimation Project first?.
        /// </summary>
        internal static string ProjectEstimateForm_SaveCurrentGuesstimationProject {
            get {
                return ResourceManager.GetString("ProjectEstimateForm_SaveCurrentGuesstimationProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Guesstimation Project?.
        /// </summary>
        internal static string ProjectEstimateForm_SaveCurrentGuesstimationProjectCaption {
            get {
                return ResourceManager.GetString("ProjectEstimateForm_SaveCurrentGuesstimationProjectCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save JSON Guesstimate Project.
        /// </summary>
        internal static string ProjectEstimateForm_SaveGuesstimationProject {
            get {
                return ResourceManager.GetString("ProjectEstimateForm_SaveGuesstimationProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Guesstimation Project|*.json.
        /// </summary>
        internal static string ProjectEstimateForm_SaveGuesstimationProjectFilter {
            get {
                return ResourceManager.GetString("ProjectEstimateForm_SaveGuesstimationProjectFilter", resourceCulture);
            }
        }
    }
}
